#spring:
#  application:
#    name: Sigma Finance
#    security:
#      jwt:
#        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#        expiration: 900000 # 15 minutes
#        refresh-token:
#          expiration: 1209600000 # 14 days
#  profiles:
#    active: prod

server:
  port: 8080

# Общие параметры приложения
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000 # 15 minutes
      refresh-token:
        expiration: 1209600000 # 14 days


currency:
  apiKey: 1e4044b19708743514f8ce5b

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db.tkczpzeamfwnzntujxoj.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: BEnByCtika4xy68v
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
